require 'pry'
require 'colorize'
require 'nokogiri'
require 'open-uri'

require_relative './quote.rb'
require_relative './category.rb'
require_relative './scraper.rb'
require_relative './author.rb'
require_relative './cli.rb'